# Sample metadata sheet
metadata: #"config/metadata.tsv"
metadataCohortColumns: 
      - 'aim_species'


# for reference, if using cloud access
# columns in ag3.sample_metadata() metadata
#['sample_id', 'partner_sample_id', 'contributor', 'country', 'location',
#       'year', 'month', 'latitude', 'longitude', 'sex_call', 'sample_set',
#       'release', 'aim_species_fraction_colu', 'aim_species_fraction_arab',
#       'aim_species_gambcolu_arabiensis', 'aim_species_gambiae_coluzzii',
#       'aim_species', 'country_ISO', 'adm1_name', 'adm1_ISO', 'adm2_name',
#       'taxon', 'cohort_admin1_year', 'cohort_admin1_month',
#       'cohort_admin2_year', 'cohort_admin2_month'],


# Dataset name
dataset: 'ag3_ug'

# If no VCF input is provided, VCFs will be written from the Zarr files
# If no Zarr input is provided, Zarr arrays will be written from the VCF files
VObsCloud:
      activate: True
      sample_sets: ['AG1000G-UG']
Zarr:
      activate: False
      Genotypes: 
      Positions: 
      SiteFilters: 
VCF:
      activate: False
      biallelic: 
      multiallelic:

# Paths for reference files 
reference:
      genome:
            "resources/reference/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa"

# Chromosome names. Should correspond to the reference fasta/gff files. 
contigs: ['2L', '2R', '3L', '3R', 'X']

# Modules #
PopulationStructure:
      PCA:
            activate: False
            colourColumns: ['aim_species']
  #    SummaryStatistics:
   #         activate : False
   #   fineStructure:
    #        activate: True
      Relatedness:
            activate: False
      f2_variants: 
            activate: False     # Doubletons

SpatialAnalyses:
      Fst_V_GeographicDistance:
            activate: False
            minimumLocationSampleSize: 5

Selection:
      VariantsOfInterest: 
            activate: True
            path: "resources/VariantsOfInterest.tsv"
            map: False
            minPopSize: 10
      G12:
            activate: False
            windowSize: 
            windowStep: 
            cutHeight: 
      G123:
            activate: False
            windowSize: 1200
            windowStep: 600
            cutHeight: 6
      H12:
            activate: False
            windowSize:
            windowStep:
      PBS:
            activate: False
            windowSize: 1200
            windowStep: 600
            metadataComparatorColumn: 'mining'


# Run analysis with compkaryo to determine proportion % karyotype
karyotype:
        activate: False
        inversions:
             - "2La"
             - "2Rj"
             - "2Rb"
             - "2Rc_col"
             - "2Rc_gam"
             - "2Rd"
             - "2Ru"
